apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devtools
  namespace: devtools
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: devtools.local
      http:
        paths:
          - path: /(api/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
