"""Static reference data: HTTP status codes and common MIME types."""

HTTP_STATUSES: list[dict] = [
    # 1xx
    {"code": 100, "name": "Continue", "description": "Initial request received; client should continue."},
    {"code": 101, "name": "Switching Protocols", "description": "Protocol switch requested by client honored."},
    {"code": 103, "name": "Early Hints", "description": "Preload hints before the final response."},
    # 2xx
    {"code": 200, "name": "OK", "description": "Request succeeded."},
    {"code": 201, "name": "Created", "description": "Resource created."},
    {"code": 202, "name": "Accepted", "description": "Request accepted but not yet processed."},
    {"code": 204, "name": "No Content", "description": "Successful with no response body."},
    {"code": 206, "name": "Partial Content", "description": "Range request fulfilled."},
    # 3xx
    {"code": 301, "name": "Moved Permanently", "description": "Resource has moved; clients should update links."},
    {"code": 302, "name": "Found", "description": "Temporary redirect."},
    {"code": 303, "name": "See Other", "description": "Redirect using GET to another resource."},
    {"code": 304, "name": "Not Modified", "description": "Cached copy is still valid."},
    {"code": 307, "name": "Temporary Redirect", "description": "Temporary redirect; method preserved."},
    {"code": 308, "name": "Permanent Redirect", "description": "Permanent redirect; method preserved."},
    # 4xx
    {"code": 400, "name": "Bad Request", "description": "The request is malformed."},
    {"code": 401, "name": "Unauthorized", "description": "Authentication required or failed."},
    {"code": 403, "name": "Forbidden", "description": "Client lacks permission."},
    {"code": 404, "name": "Not Found", "description": "Resource does not exist."},
    {"code": 405, "name": "Method Not Allowed", "description": "HTTP method not allowed for this resource."},
    {"code": 408, "name": "Request Timeout", "description": "Server timed out waiting for the request."},
    {"code": 409, "name": "Conflict", "description": "Request conflicts with current state."},
    {"code": 410, "name": "Gone", "description": "Resource removed permanently."},
    {"code": 413, "name": "Payload Too Large", "description": "Request body exceeded server limits."},
    {"code": 415, "name": "Unsupported Media Type", "description": "Media type not supported."},
    {"code": 418, "name": "I'm a teapot", "description": "RFC 2324 joke status code."},
    {"code": 422, "name": "Unprocessable Entity", "description": "Validation failed."},
    {"code": 425, "name": "Too Early", "description": "Server unwilling to risk replay attack."},
    {"code": 429, "name": "Too Many Requests", "description": "Rate-limited."},
    # 5xx
    {"code": 500, "name": "Internal Server Error", "description": "Server-side fault."},
    {"code": 501, "name": "Not Implemented", "description": "Server does not support the request."},
    {"code": 502, "name": "Bad Gateway", "description": "Upstream returned an invalid response."},
    {"code": 503, "name": "Service Unavailable", "description": "Server temporarily down or overloaded."},
    {"code": 504, "name": "Gateway Timeout", "description": "Upstream timed out."},
    {"code": 507, "name": "Insufficient Storage", "description": "Server cannot store the request."},
]


MIME_TYPES: list[dict] = [
    {"type": "application/json", "extensions": ["json"], "description": "JSON document."},
    {"type": "application/xml", "extensions": ["xml"], "description": "XML document."},
    {"type": "application/yaml", "extensions": ["yaml", "yml"], "description": "YAML document."},
    {"type": "application/toml", "extensions": ["toml"], "description": "TOML document."},
    {"type": "application/pdf", "extensions": ["pdf"], "description": "PDF document."},
    {"type": "application/zip", "extensions": ["zip"], "description": "Zip archive."},
    {"type": "application/gzip", "extensions": ["gz"], "description": "Gzip compressed file."},
    {"type": "application/octet-stream", "extensions": ["bin"], "description": "Arbitrary binary data."},
    {"type": "application/x-www-form-urlencoded", "extensions": [], "description": "URL-encoded form body."},
    {"type": "multipart/form-data", "extensions": [], "description": "Multipart form body (file uploads)."},
    {"type": "text/plain", "extensions": ["txt"], "description": "Plain text."},
    {"type": "text/html", "extensions": ["html", "htm"], "description": "HTML document."},
    {"type": "text/css", "extensions": ["css"], "description": "Cascading Style Sheets."},
    {"type": "text/csv", "extensions": ["csv"], "description": "Comma-separated values."},
    {"type": "text/markdown", "extensions": ["md", "markdown"], "description": "Markdown source."},
    {"type": "text/javascript", "extensions": ["js", "mjs"], "description": "JavaScript source."},
    {"type": "image/png", "extensions": ["png"], "description": "PNG image."},
    {"type": "image/jpeg", "extensions": ["jpg", "jpeg"], "description": "JPEG image."},
    {"type": "image/gif", "extensions": ["gif"], "description": "GIF image."},
    {"type": "image/svg+xml", "extensions": ["svg"], "description": "SVG vector image."},
    {"type": "image/webp", "extensions": ["webp"], "description": "WebP image."},
    {"type": "audio/mpeg", "extensions": ["mp3"], "description": "MP3 audio."},
    {"type": "audio/wav", "extensions": ["wav"], "description": "WAV audio."},
    {"type": "video/mp4", "extensions": ["mp4"], "description": "MP4 video."},
    {"type": "video/webm", "extensions": ["webm"], "description": "WebM video."},
    {"type": "font/woff", "extensions": ["woff"], "description": "Web Open Font Format."},
    {"type": "font/woff2", "extensions": ["woff2"], "description": "WOFF2 font."},
    {"type": "font/ttf", "extensions": ["ttf"], "description": "TrueType font."},
]
