name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the project! 🎉 We're thrilled to have you here and are eager to see your contributions. 
                        Please make sure to read our [contribution guidelines](LINK_TO_YOUR_GUIDELINES) to get started. 
                        If you have any questions, don't hesitate to ask in the issue comments."
        pr-message: "Thank you for submitting your first pull request! 🚀 We're excited to review it. 
                    While you wait, if you have any questions about the process, feel free to ask."
